name: sm
channels:
  - bioconda
#  - r
#  - conda-forge
#  - defaults
dependencies:
#  - python=3.9.7
#  - numpy
#  - biopython
#  - pandas
  - snakemake

  - starcode
#  - snakemake
#  - snakemake-minimal=7.21.0
  - trim-galore
  - pip


